### ISSUE TITLE
Missing 'else' block

### ISSUE THREAD

**Issue by vmartirosyan** [sona13asatryan/HugeInt#2]
https://github.com/sona13asatryan/HugeInt/blob/34bbd245abe8c56cf0d723bf4d3094c8e82f76a3/HugeInt.cpp#L13

What if the input was invalid? Throw exception or do something else in order to let the user know about problems.

**Comment by sona13asatryan** [comment]
In case if the input is invalid, input_validation function will throw a message and call abort().
https://github.com/sona13asatryan/HugeInt/blob/34bbd245abe8c56cf0d723bf4d3094c8e82f76a3/HugeInt.cpp#L197
